// vegefoods.reactui/src/components/Profile.jsx
import { useState, useEffect } from "react";
import { Link, useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";

import apihelper from '../helpers/apihelper';

const Profile = () => {
    const [id, setId] = useState("");
    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
    const [confirmpassword, setConfirmPassword] = useState("");
    const [firstname, setFirstName] = useState("");
    const [lastname, setLastName] = useState("");
    const [phone, setPhone] = useState("");
    const [country, setCountry] = useState("vietnam");
    const [address, setAddress] = useState("");
    const [gender, setGender] = useState("female");
    const [dateofbirth, setDateOfBirth] = useState(new Date());

    const navigate = useNavigate();
    let email_vegefoods = localStorage.getItem('email_vegefoods');
    useEffect(() => {
        
        if(email_vegefoods === '' || email_vegefoods === null){
            navigate('/login');
        }
        else{        

            apihelper.get("/users/GetUserByEmail/" + email_vegefoods)
            .then(response => {
                // Handle the response
                //console.log(response.data);
                if (response.status === 200) {
                    setId(response.data.id);
                    setEmail(response.data.email);
                    setPassword(response.data.password);
                    setConfirmPassword(response.data.password);
                    setFirstName(response.data.firstName);
                    setLastName(response.data.lastName);
                    setPhone(response.data.phone);
                    setCountry(response.data.country);
                    setAddress(response.data.address);
                    setGender(response.data.gender);
                    setDateOfBirth(response.data.dateOfBirth);
                }
                else
                    throw new Error(response.status);
            })
            .catch(error => {
                // Handle errors
                toast.error('Get Profile Information Failed due to :' + error.message);
            });
        }             

     }, []);

    const IsValidate = () => {
        let isproceed = true;
        let errormessage = 'Please enter the value in ';       
        if (email === null || email === '') {
            isproceed = false;
            errormessage += ' Email';
        }
        if (password === null || password === '') {
            isproceed = false;
            errormessage += ' Password';
        }        
        //console.log(password, confirmpassword)
        if (confirmpassword === null || confirmpassword === '' || password !== confirmpassword) {
            isproceed = false;
            errormessage += ' Confirm Password: not match Password';
        } 
        if(!isproceed){
            toast.warning(errormessage)
        }else{
            if(/^[a-zA-Z0-9]+@[a-zA-Z0-9]+\.[A-Za-z]+$/.test(email)){

            }else{
                isproceed = false;
                toast.warning('Please enter the valid email')
            }
        }
        return isproceed;
    }

    const handlesubmit = (e) => {
        e.preventDefault();
        let profileUser = { 
            Id: id, 
            Email: email,
            Password: password,
            ConfirmPassword: confirmpassword,
            FirstName: firstname || "",
            DateOfBirth: dateofbirth,
            LastName: lastname || "",
            Phone: phone || "",
            Country: country || "",
            Gender: gender || "",
            Address: address || ""
        }
        if (IsValidate()) {
            //console.log(profileUser);       
            apihelper.put("/users/" + id, profileUser) 
            .then(response => {
                //console.log(response.status);
                if(response.status === 200)
                    toast.success('Updated Profile successfully.')
            })
            .catch(error => {                
                toast.error('There was an error!', error);
            });             
        }
    }

    return (
        <div className="ftco-section">
            <div className="offset-lg-3 col-lg-6">
                <h1>Profile Information</h1>
                <form onSubmit={handlesubmit}>
                    <input type="hidden" value={id} className="form-control"></input> 
                    <div className="form-group row text-right">
                        <label htmlFor="email" className="col-sm-4 col-form-label">Email</label>
                        <div className="col-sm-8">
                        <input type="text" readOnly id="email" className="form-control-plaintext"  value={email} />
                        </div>
                    </div>
                    <div className="form-group row text-right">
                        <label htmlFor="password" className="col-sm-4 col-form-label">Password <span className="errmsg">*</span></label>
                        <div className="col-sm-8">
                        <input id="password" value={password} onChange={e => setPassword(e.target.value)} type="password" className="form-control"  placeholder="Password" />
                        </div>
                    </div>
                    <div className="form-group row text-right">
                        <label htmlFor="confirmPassword" className="col-sm-4 col-form-label">Confirm Password <span className="errmsg">*</span></label>
                        <div className="col-sm-8">
                        <input id="confirmPassword" value={confirmpassword} onChange={e => setConfirmPassword(e.target.value)} type="password" className="form-control"  placeholder="Confirm Password" />
                        </div>
                    </div>
                    <div className="form-group row text-right">
                        <label htmlFor="firstname" className="col-sm-4 col-form-label">First Name</label>
                        <div className="col-sm-8">
                        <input id="firstname" value={firstname || ""} onChange={e => setFirstName(e.target.value)} className="form-control"></input>
                        </div>
                    </div>
                    <div className="form-group row text-right">
                        <label htmlFor="lastname" className="col-sm-4 col-form-label">Last Name</label>
                        <div className="col-sm-8">
                        <input id="lastname" value={lastname || ""} onChange={e => setLastName(e.target.value)} className="form-control"></input>
                        </div>
                    </div>
                    <div className="form-group row text-right">
                        <label htmlFor="dateOfBirth" className="col-sm-4 col-form-label">Date Of Birth</label>
                        &nbsp;&nbsp;&nbsp;&nbsp;
                        <DatePicker id="dateOfBirth" showIcon selected={dateofbirth || ""} onChange={(date) => setDateOfBirth(date)} />
                        
                    </div>
                    <div className="form-group row text-right">
                        <label htmlFor="phone" className="col-sm-4 col-form-label">Phone</label>
                        <div className="col-sm-8">
                        <input id="phone" value={phone || ""} onChange={e => setPhone(e.target.value)} className="form-control"></input>
                        </div>
                    </div>

                    <div className="form-group row text-right">
                        <label htmlFor="country" className="col-sm-4 col-form-label">Country</label>
                        <div className="col-sm-8">
                            <select id="country" value={country || "vietnam"} onChange={e => setCountry(e.target.value)} className="form-control">
                                <option value="india">India</option>
                                <option value="usa">USA</option>
                                <option value="singapore">Singapore</option>
                                <option value="vietnam">VietNam</option>
                            </select>
                        </div>
                    </div>
                    <div className="form-group row text-right">                       
                        <label htmlFor="gender" className="col-sm-4 col-form-label">Gender</label>
                        &nbsp;&nbsp;&nbsp;&nbsp;
                        <input id="gender" type="radio" checked={gender === 'male'} onChange={e => setGender(e.target.value)} name="gender" value="male" className="app-check"></input>
                        &nbsp;&nbsp; 
                        <label>Male</label>&nbsp;&nbsp; &nbsp;&nbsp; 
                        <input type="radio" checked={gender === 'female'} onChange={e => setGender(e.target.value)} name="gender" value="female" className="app-check"></input>
                        &nbsp;&nbsp; 
                        <label>Female</label>
                    </div>
                    <div className="form-group row text-right">
                        <label htmlFor="address" className="col-sm-4 col-form-label">Address</label>
                        <div className="col-sm-8">
                        <textarea id="address" value={address || ""} onChange={e => setAddress(e.target.value)} className="form-control"></textarea>
                        </div>
                    </div>
                    <div className="text-center">
                        <button type="submit" className="btn btn-primary">Update</button> &nbsp;&nbsp; 
                        <Link to={'/'} className="btn btn-danger">Close</Link>
                    </div>
                </form>                
            </div>
        </div>
    );
}

export default Profile;

// vegefoods.angularui/src/app/Pages/users/profile/profile.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute,Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { UserService } from '../../../Services/user.service';
// need to remove component also
//import { ChangepasswordComponent } from '../../partials/changepassword/changepassword.component';
import { ToastrService } from 'ngx-toastr';


@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrl: './profile.component.css'
})
export class ProfileComponent implements OnInit{
  userId !: any;
  email !: any;
  user!: any;
  userForm!: FormGroup;
  userPasswordForm!: FormGroup;
  isLoading: boolean = false;
  errors: any;

  constructor(private activatedRoute: ActivatedRoute,
    private userService: UserService,
    private formBuilder: FormBuilder,
   private toastr: ToastrService,
  private router: Router) {

  this.userForm = this.formBuilder.group({
    id: ['', Validators.required],
    email: ['', Validators.required],
    password: ['', Validators.required],
    firstName: ['', Validators.maxLength(50)],
    lastName: ['', Validators.maxLength(50)],
    //phone: ['', [Validators.required, validInteger]],
    phone: ['', Validators.maxLength(10)],
    country: ['', Validators.maxLength(50)],
    address: ['', Validators.maxLength(200)],
    gender: ['', Validators.maxLength(10)],              
    dateOfBirth: ['', Validators.maxLength(10)],              
    });

    this.userPasswordForm = this.formBuilder.group({
      id: ['', Validators.required],
      currentpassword: ['', Validators.required],
      newpassword: ['', Validators.required],       
      confirmpassword: ['', Validators.required],             
      }); 
  }
  ngOnInit(): void {
    this.email = localStorage.getItem('email_vegefoods_angular');

    if(this.email === '')
      this.router.navigate(['/login']);

    this.userService.getUserByEmail(this.email).subscribe(
      (res: any) => {
      this.user = res;
      this.userId = res.id;
      this.userForm.patchValue(this.user);
      this.userPasswordForm.patchValue(this.user);
      }
    );
  }

  updateUser() {
    
    this.isLoading = true;
    //if (this.userForm.valid) { 
      console.log(this.userId);
      console.log('updating')
       this.userService.updateUser(this.userForm.value, this.userId).subscribe({
        next: (res: any) => {
          this.isLoading = false;
          this.toastr.success('Updated profile successfully', 'Information');
        },
        error: (err: any) => {
          throw err;
        }
      });      
      
    // }    
  }

  cancelUpdate(){
    this.router.navigate(['/home']);
  }
}


<!-- Profile Page Start -->
<div class="container-fluid page-padding-top">
    <h1 class="ms-5 ps-5 text-secondary">Profile</h1>      
    <div class="container">
        <div class="col-3">
            <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#popupChangePassword">Change Password</button>           
          </div>
        <form [formGroup]="userForm"  (ngSubmit)="updateUser()">
            <input type="hidden" formControlName="id" className="form-control" />
            <div class="row g-5">
                <div class="col-md-12 col-lg-6 col-xl-7">
                    <div class="form-item">
                        <label class="form-label my-3">Email Address<sup>*</sup></label>
                        <input type="email" formControlName="email"  class="form-control" readonly>
                    </div>             
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="form-item w-100">
                                <label class="form-label my-3">First Name<sup>*</sup></label>
                                <input type="text" formControlName="firstName"  class="form-control">
                            </div>
                        </div>
                        <div class="col-md-12 col-lg-6">
                            <div class="form-item w-100">
                                <label class="form-label my-3">Last Name<sup>*</sup></label>
                                <input type="text" formControlName="lastName"  class="form-control">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="form-item w-100">
                                <label class="form-label my-3">Date Of Birth<sup>*</sup></label>
                                <input type="text" formControlName="dateOfBirth" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-12 col-lg-6">
                            <div class="form-item w-100">
                                <label class="form-label my-3">Country<sup>*</sup></label>
                                <input type="text" formControlName="country" class="form-control">
                            </div>
                        </div>
                    </div>    
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="form-item w-100">
                                <label class="form-label my-3">Phone<sup>*</sup></label>
                                <input type="text" formControlName="phone" class="form-control">
                            </div>
                        </div>
                        
                    </div>                          

                    <div class="form-item">
                        <label class="form-label my-3">Address<sup>*</sup></label>
                        <textarea name="text" class="form-control" formControlName="address" spellcheck="false" cols="30" rows="4" placeholder="Enter Address"></textarea>
                    </div>         
                    <div class="mt-4">                        
                        <button class="btn border-secondary rounded-pill px-4 py-3 text-primary" type="submit">Save</button>
                        &nbsp;&nbsp;&nbsp;
                        <button (click)="cancelUpdate()" class="btn border-secondary rounded-pill px-4 py-3 text-danger" type="button">Cancel</button>
                    </div>       
                </div>                        
            </div>
        </form>
    </div>
</div>
<!-- Profile Page End -->

<div class="modal" id="popupChangePassword">
    <app-changepassword  [userId]="userId"></app-changepassword>    
  </div>
